### ISSUE TITLE
Error executing your script

### ISSUE THREAD

**Issue by CustardFlan** [Stat1cV01D/navidrome_lastfm_import#1]
I there!

I followed the steps to export my last.fm playcount, cloned this repository and, when i try to use it, i receive this error:

`Traceback (most recent call last):
  File "/home/custard/navidrome_lastfm_import/main.py", line 184, in <module>
    main()
  File "/home/custard/navidrome_lastfm_import/main.py", line 160, in main
    track_id = get_track_id(db_cursor,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/custard/navidrome_lastfm_import/main.py", line 112, in get_track_id
    {"artist": artist.lower(), "name": name.lower()}),
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'`

What i'm doing wrong?

Thanks in advance

**Comment by Stat1cV01D** [comment]
Hi, @CustardFlan !

Sorry for a late reply. It appears that a track name has not been read properly. Can I have a look at your file from the last.fm export site? If not, then I would need to know how recent was the export done. There might have been changes in the export data format that I've missed.
_____

I could also use the `output.log` file which is produced next to the script - there might be useful information too.

**Comment by CustardFlan** [comment]
Nice!
The output.log is empty after running the script
and, this is a sample of the export, these are the loved tracks, i have another with the entire scrobbling history, but it's a 168 MB file, the format is the same, the tool used is https://mainstream.ghan.nl/export.html

Sample:

https://paaster.io/jPHeZCfenNUfGFyuLenfz#_ph8r-28DcC36yts5fqP2wkFmB3XGsQvuBCJlrdv_bs

These files doesn't have newlines, it's that normal?

**Comment by Stat1cV01D** [comment]
The "loved tracks" seems to be working on my end so far.

The "scrobbling history" is not supported though - I haven't worked on it yet. Let me know if I should look into that.

And no new lines in JSON is OK - they are frequently minified this way to shrink the size.
I've pushed a small commit that would indicate if the input format is invalid.

**Comment by CustardFlan** [comment]
It would be neat if you work in play count syncing! :D 

I have opened a discussion here, but nobody replied so far
https://github.com/navidrome/navidrome/discussions/3454

The idea is:

Make a GET request like this:
https://ws.audioscrobbler.com/2.0/?autocorrect=1&username=CustardSandS&format=json&api_key=THEAPIKEY&method=track.getInfo&artist=Daft+Punk&track=WDPK+83.7+FM

Using the data already available on the DB, and, updating the loved status or the play count, i'm not so good in python or SQL, but, i think you get the idea, and can do this!
Why updating using request to the last.fm API and not use the export instead? Well, because the scrobbles get autocorrected anyway in that service, and, i assume if one use the navidrome software, the tags existing in the music collection are well organized, and, i have tested a small batch of albums, and the data can be correllated easilly

It's only an idea, but, take that on mind

**Comment by Stat1cV01D** [comment]
OK. I will try to accomodate for the "play count" feature in the existing code, but it will take time.

**Comment by CustardFlan** [comment]
Thank you!

**Comment by Stat1cV01D** [comment]
@CustardFlan 

Coming back with the news: I've added the an ability to used scrobbles in JSON format from the same site together with the favorites. It works significantly longer as there are many more scrobbles than favorite tracks, but as the structure of both files is the same it should work fine.

**Comment by CustardFlan** [comment]
It WORKS!

Thank you!

Only a little observation...

My current DB doen't have the 'ann_id' column
I have added that using "DB Browser for SQLite" in Fedora, so, no more errors

Now, i'm happy, 13 years of play history now are back
